# A JupyterHub Helm chart config containing only auth relevant config, and is
# meant to be used alongside another configuration.

hub:
  services:
    binder:
      oauth_no_confirm: true
      oauth_redirect_uri: "http://127.0.0.1:8585/oauth_callback"
  config:
    JupyterHub:
      authenticator_class: "dummy"
    DummyAuthenticator:
      password: "dummy"
    BinderSpawner:
      auth_enabled: true
  loadRoles:
    user:
      scopes:
        - self
        - "access:services"
