name: binderhub
channels:
  - conda-forge
dependencies:
- python=3.5
- traitlets>=4.1
- sphinx>=1.4, !=1.5.4
- sphinx_rtd_theme
- mne
- graphviz
- pip:
  - jupyter_alabaster_theme
  - recommonmark==0.4.0
  - pygraphviz
