kind: ConfigMap
apiVersion: v1
metadata:
  name: binder-config
data:
  binder.debug: {{ .Values.debug.enabled | quote }}
  binder.use-registry: {{ .Values.registry.enabled | quote }}
  {{ if .Values.registry.enabled -}}
  binder.push-secret: binder-secret
  binder.registry.host: {{ .Values.registry.host | quote }}
  {{ if .Values.registry.authHost -}}
  binder.registry.auth-host: {{ .Values.registry.authHost | quote }}
  {{- end }}
  binder.registry.auth-token-url: {{ .Values.registry.authTokenUrl | quote }}
  {{ end -}}
  {{ if .Values.googleAnalyticsCode -}}
  binder.google-analytics-code: {{ .Values.googleAnalyticsCode | quote }}
  {{- end }}
  {{ if .Values.googleAnalyticsDomain -}}
  binder.google-analytics-domain: {{ .Values.googleAnalyticsDomain | quote }}
  {{- end }}
  binder.cors: {{ toJson .Values.cors | quote }}
  binder.per-repo-quota: {{ .Values.perRepoQuota | quote }}
  binder.registry.prefix: {{ .Values.registry.prefix | quote }}
  binder.repo2docker-image: {{ .Values.build.repo2dockerImage | quote }}
  {{ if .Values.build.nodeSelector -}}
  binder.build-node-selector: {{ toJson .Values.build.nodeSelector | quote }}
  {{- end }}
  {{ if .Values.build.appendix -}}
  binder.appendix: {{ .Values.build.appendix | quote }}
  {{- end }}

  binder.retries.count: {{ .Values.retries.count | quote }}
  binder.retries.delay: {{ .Values.retries.delay | quote }}

  binder.hub-url: {{ .Values.hub.url | quote }}
  binder.base_url: {{ .Values.baseUrl | quote }}

  {{ if .Values.github.hostname -}}
  github.hostname: {{ .Values.github.hostname | quote }}
  {{- end }}
  {{ if .Values.gitlab.hostname -}}
  gitlab.hostname: {{ .Values.gitlab.hostname | quote }}
  {{- end }}

  {{ if .Values.template.variables -}}
  template.variables: {{ toJson .Values.template.variables | quote }}
  {{- end }}
  {{ if .Values.template.path -}}
  template.path: {{ .Values.template.path | quote }}
  {{ if .Values.template.static.path -}}
  template.static.path: {{ .Values.template.static.path | quote }}
  {{- end }}
  {{ if .Values.template.static.urlPrefix -}}
  template.static.url-prefix: {{ .Values.template.static.urlPrefix | quote }}
  {{- end }}
  {{- end }}

  dind.enabled: {{ .Values.dind.enabled | quote }}
  {{ if .Values.dind.enabled }}
  dind.host-socket-dir: {{ .Values.dind.hostSocketDir | quote }}
  {{ end }}

  {{ if .Values.extraConfig }}
  {{ range $key, $value := .Values.extraConfig -}}
  extra-config.{{ $key }}.py: |
{{ $value | indent 4 }}
  {{- end }}
  {{- end }}
