# This workflow provides a diff of the rendered Helm chart's templates with the
# latest released dev version of the chart.
#
name: Helm diff

on:
  pull_request:
    paths:
      - ".github/workflows/diff.yml"
      - "helm-chart/binderhub/**"
  push:
    paths:
      - ".github/workflows/diff.yml"
      - "helm-chart/binderhub/**"
    branches-ignore:
      - "dependabot/**"
      - "pre-commit-ci-update-config"
      - "update-*"
  workflow_dispatch:

jobs:
  diff-rendered-templates:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: jupyterhub/action-k3s-helm@v4
        with:
          k3s-channel: stable
          metrics-enabled: false
          traefik-enabled: false
          docker-enabled: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install helm diff plugin, update local chart dependencies
        run: |
          helm plugin install https://github.com/databus23/helm-diff
          helm dependency update ./helm-chart/binderhub

      - name: "Install latest released dev chart"
        run: |
          UPGRADE_FROM_VERSION=$(curl -sSL https://jupyterhub.github.io/helm-chart/info.json | jq -er '.binderhub.dev')

          # NOTE: We change the directory so binderhub the chart name won't be
          #       misunderstood as the local folder name.
          # validation is disabled, because the config is for a different version!
          cd testing

          old_config="../testing/k8s-binder-k8s-hub/binderhub-chart-config-old.yaml"
          if [ -f "$old_config" ]; then
            echo "using old config"
          else
            old_config="../testing/k8s-binder-k8s-hub/binderhub-chart-config.yaml"
          fi

          helm install binderhub-test binderhub \
              --values "$old_config" \
              --repo https://jupyterhub.github.io/helm-chart/ \
              --disable-openapi-validation \
              --version=$UPGRADE_FROM_VERSION

      - name: "Helm diff latest released dev chart with local chart"
        run: |
          echo "NOTE: For the helm diff, we have not updated the Chart.yaml"
          echo "      version or image tags using chartpress."
          echo

          helm diff upgrade binderhub-test helm-chart/binderhub \
              --values testing/k8s-binder-k8s-hub/binderhub-chart-config.yaml \
              --context=3
